# Thông tin cá nhân
name: PHUC TRAN NGOC
title: Senior Data Engineer/ Data Architect
email: ptrann310@gmail.com
phone: "+84 368609837"
location: Hanoi, Vietnam
linkedin_username: "phuc-tran-855482221" # Thay bằng username LinkedIn của bạn
github_username: "nptran"   # Thay bằng username GitHub của bạn
profile_picture: /profile.png

# Cấu hình website
remote_theme: pages-themes/minimal@v0.2.0 # Giao diện cơ bản, sạch sẽ
plugins:
  - jekyll-remote-theme
